### ISSUE TITLE
Context menu key doesn't work anymore

### ISSUE THREAD

**Issue by Chris2011** [AlexFalappa/nb-springboot#127] opened 2018-01-09 11:32 UTC
I installed your plugin and after installing it, the context key on my keyboard doesn't work anymore. Can you please fix it, this key is essential and should work like before.

Cheers

Chris

**Comment by AlexFalappa** [comment] 2018-01-11 12:29
Possible duplicate of #106

**Comment by Chris2011** [comment] 2018-04-12 13:51
I wanted to contribute, but I couldn't find time. I think this happens, because of you are listening to a key event, right? If yes, why? For which case? If not then there must be an other bug.

**Comment by AlexFalappa** [comment] 2018-04-15 10:09
@Chris2011 I found that this behaviour is a side effect of the fact that I introduced a `ContextGlobalProvider` proxy with the `com.github.alexfalappa.nbspringboot.actions.GlobalActionContextProxy` class.

If I disable it the menu key gets working again but the _Spring Boot Restart_ button enables only when the project node in the Projects view is selected. I would like it to behave like the Run/Debug buttons that are enabled and working even if a source file is selected.

**Comment by Chris2011** [comment] 2018-04-16 06:11
Ok, maybe you have to check another way. Maybe not use the GlobalActionContextProxy?

**Comment by Chris2011** [comment] 2018-05-28 08:15
Is it possible to make a hotfix there, do you have any solution for this? I mean ok, the workaround for me is to deactivate your plugin. Just saying.

**Comment by toniaca** [comment] 2018-05-31 10:09
Hi @AlexFalappa 

I would like to help you to resolve the tickets. I don't have experience developing plugins but I can learn. What do you think about to start with this ticket?.

Cheers.

**Comment by AlexFalappa** [comment] 2018-06-01 09:15
Sure @toniperezfer !
As I said above the easy but sub-optimal fix is to remove the `com.github.alexfalappa.nbspringboot.actions.GlobalActionContextProxy` class, a more elaborate fix requires studying the NetBeans source code and see how the Run Project and Debug Project actions (activated via toolbar and menu) work with respect to enablement and try to replicate their behaviour.

The main wish is to make the Restart action enabled whenever a file in a project is selected and to operate on the project that source file is in.

**Closed** 2018-07-26 19:10 UTC
Labels: bug, help wanted

**Comment by AlexFalappa** [comment] 2018-07-26 21:33
@Chris2011 I finally found a way to properly fix this issue.

The answer was in NetBeans wiki.

I also improved the restart action enablement logic so that restart is always available when editing relevant project files like sources and application.properties files.

Could you please have a look at the latest version just released?
