### ISSUE TITLE
NullPointerException when opening properties

### ISSUE THREAD

**Issue by neftalyluis** [AlexFalappa/nb-springboot#76] opened 2017-02-22 18:28 UTC
Hi, 

When i try to check or fill on any of the options from Spring Boot menu on the Project Properties, NetBeans shows this Stacktrace

I'm using the last version of the plugin (1.4) and NetBeans 8.1

``` 
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.updateVmOptions(BootPanel.java:520)
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.access$100(BootPanel.java:50)
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel$2.insertUpdate(BootPanel.java:130)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1328)
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1065)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1115)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1087)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:128)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1072)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl$1.run(CustomizerProviderImpl.java:188)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:93)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:89)
	at org.openide.util.Mutex.readAccess(Mutex.java:260)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:170)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:138)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:133)
	at org.netbeans.modules.project.ui.actions.CustomizeProject$1$1.run(CustomizeProject.java:160)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



```

**Comment by AlexFalappa** [comment] 2017-02-23 10:56
I cannot reproduce this exception neither with the current development version nor with v1.4.

Could you please detail exactly how this presented?
Have you also modified something in the Project `Properties` > `Actions` page?
Could you please attach the content of the **Set Properties* text area in that page?

**Comment by neftalyluis** [comment] 2017-02-23 17:59
![actions](https://cloud.githubusercontent.com/assets/6645384/23272019/4a3a841e-f9bf-11e6-8127-0a291723564d.png)


This is the only action that i've modified to run my project inside NetBeans, the other actions were left as is

**Comment by AlexFalappa** [comment] 2017-02-23 22:06
A-ha that could be the cause. NB Spring Boot plugin should be in control of the project actions and you should not make modifications to them. 

I will try to reproduce your situation to make the plugin more robust. In the meantime if you would like to recover your project try to copy the properties from another project created with the Spring Initializr wizard and adjust them accordingly (e.g. adapt the main class)

**Comment by AlexFalappa** [comment] 2017-02-24 09:32
I think I reproduced your situation: you haven't set the `Run/Debug with spring boot maven plugin` option when you generated the project right?
Or you modified an existing maven project and added the necessary bits to make it a Spring Boot project, right?

In that case the plugin tries to modify the **Debug Project** action property but fails because it has not been already overridden (i.e. it does not use the maven spring boot plugin).

Then as a workaround modify also the **Debug Project** action and set the _Execute Goals_ field to `spring-boot:run` while in the _Set Properties_ text area override the existing properties with the following:
```
run.jvmArguments=-Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=${jpda.address}
jpda.listen=true
```

**Comment by AlexFalappa** [comment] 2017-02-24 09:39
To make the plugin more robust I will enable the *Spring Boot* project panel only if the spring maven plugin is used both to run and debug the project, currently only a check on the **Run project** action is made.

**Comment by AlexFalappa** [comment] 2017-02-24 12:50
Fixed in master.

**Closed** 2017-02-24 12:49 UTC
Labels: bug
