### ISSUE TITLE
NPE in project properties

### ISSUE THREAD

**Issue by everflux** [AlexFalappa/nb-springboot#57] opened 2016-10-29 13:30 UTC
When clicking on the Spring boot tab of project properties I get a NPE
Version: 1.3 Source: Plugin Portal

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_112; Java HotSpot(TM) 64-Bit Server VM 25.112-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_112-b15
System: Linux version 4.8.0-26-generic running on amd64; UTF-8; en_US (nb)
User directory: /home/tkruse/.netbeans/8.2
Cache directory: /home/tkruse/.cache/netbeans/8.2

```
SEVERE [global]
java.lang.NullPointerException
        at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.setModelHandle(BootPanel.java:76)
        at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanelProvider.createComponent(BootPanelProvider.java:48)
        at org.netbeans.spi.project.ui.support.ProjectCustomizer$DelegateCategoryProvider.create(ProjectCustomizer.java:629)
        at org.netbeans.modules.project.uiapi.CustomizerPane.setCategory(CustomizerPane.java:259)
        at org.netbeans.modules.project.uiapi.CustomizerPane.access$200(CustomizerPane.java:72)
        at org.netbeans.modules.project.uiapi.CustomizerPane$CategoryChangeListener.propertyChange(CustomizerPane.java:345)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at org.netbeans.modules.project.uiapi.CategoryModel.firePropertyChange(CategoryModel.java:118)
        at org.netbeans.modules.project.uiapi.CategoryModel.setCurrentCategory(CategoryModel.java:92)
        at org.netbeans.modules.project.uiapi.CategoryView.propertyChange(CategoryView.java:183)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at org.openide.explorer.ExplorerManager$2.run(ExplorerManager.java:891)
        at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
        at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:93)
        at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:89)
        at org.openide.util.Mutex.readAccess(Mutex.java:260)
        at org.openide.explorer.ExplorerManager.fireInAWT(ExplorerManager.java:888)
        at org.openide.explorer.ExplorerManager$1AtomicSetSelectedNodes.fire(ExplorerManager.java:294)
        at org.openide.explorer.ExplorerManager.setSelectedNodes(ExplorerManager.java:305)
        at org.openide.explorer.ExplorerManager$1SetExploredContextAndSelection.run(ExplorerManager.java:393)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:193)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation$1R.run(DefaultMutexImplementation.java:1037)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.doWrapperAccess(DefaultMutexImplementation.java:1054)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:183)
        at org.openide.util.Mutex.readAccess(Mutex.java:260)
        at org.openide.explorer.ExplorerManager.setExploredContextAndSelection(ExplorerManager.java:420)
        at org.openide.explorer.view.BeanTreeView.selectionChanged(BeanTreeView.java:149)
        at org.openide.explorer.view.TreeView.callSelectionChanged(TreeView.java:833)
        at org.openide.explorer.view.TreeView$TreePropertyListener.run(TreeView.java:1475)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation$1Exec.run(DefaultMutexImplementation.java:973)
        at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1938)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:979)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:942)
        at org.netbeans.modules.openide.util.DefaultMutexImplementation.postReadRequest(DefaultMutexImplementation.java:308)
        at org.openide.util.Mutex.postReadRequest(Mutex.java:371)
        at org.openide.explorer.view.TreeView$TreePropertyListener.valueChanged(TreeView.java:1444)
        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
        at javax.swing.JTree.setSelectionPath(JTree.java:1634)
        at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressedDND(BasicTreeUI.java:3586)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3545)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
        at java.awt.Component.processMouseEvent(Component.java:6530)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)

```

**Comment by AlexFalappa** [comment] 2016-10-31 08:43
Duplicate of #55.
Already closed in master, will be in next version.

**Closed by AlexFalappa** 2016-10-31 08:43 UTC
